//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NowePWI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NowePWI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta witryna wykorzystuje pliki cookie.
        /// </summary>
        public static string CoockiesInfo {
            get {
                return ResourceManager.GetString("CoockiesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czytaj.
        /// </summary>
        public static string Czytaj {
            get {
                return ResourceManager.GetString("Czytaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haslo.
        /// </summary>
        public static string Haslo {
            get {
                return ResourceManager.GetString("Haslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haslo musi zawierac wiecej niz 6 znakow i jeden specjalny znak.
        /// </summary>
        public static string HasloInfo {
            get {
                return ResourceManager.GetString("HasloInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haslo nie jest zgodne.
        /// </summary>
        public static string HasloPorownanie {
            get {
                return ResourceManager.GetString("HasloPorownanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdz haslo.
        /// </summary>
        public static string HasloPotwierdz {
            get {
                return ResourceManager.GetString("HasloPotwierdz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jestem w domu.
        /// </summary>
        public static string Jestemwdomu {
            get {
                return ResourceManager.GetString("Jestemwdomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Już jesteś zalogowany!!!.
        /// </summary>
        public static string Juzjesteszalogowany {
            get {
                return ResourceManager.GetString("Juzjesteszalogowany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string Konto {
            get {
                return ResourceManager.GetString("Konto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz być zalogowany.
        /// </summary>
        public static string MusiszZalogowac {
            get {
                return ResourceManager.GetString("MusiszZalogowac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napisz do mnie.
        /// </summary>
        public static string NapiszDoMnie {
            get {
                return ResourceManager.GetString("NapiszDoMnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mnie.
        /// </summary>
        public static string Omnie {
            get {
                return ResourceManager.GetString("Omnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Stronie.
        /// </summary>
        public static string OStronie {
            get {
                return ResourceManager.GetString("OStronie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomysl.
        /// </summary>
        public static string Pomysl {
            get {
                return ResourceManager.GetString("Pomysl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona została stworzona na potrzeby przedmiotu &quot;Programowanie w internecie&quot;. Liczę na to że, stronę przyjemnie się ogląda :).
        /// </summary>
        public static string PomyslInfo {
            get {
                return ResourceManager.GetString("PomyslInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programowanie w internecie.
        /// </summary>
        public static string PWI {
            get {
                return ResourceManager.GetString("PWI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologia.
        /// </summary>
        public static string Technologia {
            get {
                return ResourceManager.GetString("Technologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologia wykorzystana do stworzenia strony, to przede wszystkim Bootstrap, css3, html5 , JavaScript, ASP.NET ..
        /// </summary>
        public static string TechnologiaInfo {
            get {
                return ResourceManager.GetString("TechnologiaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Tytul {
            get {
                return ResourceManager.GetString("Tytul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string Wiadomosc {
            get {
                return ResourceManager.GetString("Wiadomosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz jezyk.
        /// </summary>
        public static string WybierzJezyk {
            get {
                return ResourceManager.GetString("WybierzJezyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonanie.
        /// </summary>
        public static string Wykonanie {
            get {
                return ResourceManager.GetString("Wykonanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona została napisana przy wykorzystaniu programu Brackets. Grafika znajdująca się na stronie została pobrana z darmowej strony Strona została napisana przy wykorzystaniu programu Brackets. Grafika znajdująca się na stronie została pobrana z darmowej strony pixabay.com.
        /// </summary>
        public static string WykonanieInfo {
            get {
                return ResourceManager.GetString("WykonanieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string Wyloguj {
            get {
                return ResourceManager.GetString("Wyloguj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole nie może być puste.
        /// </summary>
        public static string Wymagane {
            get {
                return ResourceManager.GetString("Wymagane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wpisales hasla.
        /// </summary>
        public static string WymaganeHaslo {
            get {
                return ResourceManager.GetString("WymaganeHaslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podales adresu e-mail.
        /// </summary>
        public static string WymaganyEmail {
            get {
                return ResourceManager.GetString("WymaganyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Wyslij {
            get {
                return ResourceManager.GetString("Wyslij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Zaloguj {
            get {
                return ResourceManager.GetString("Zaloguj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string Zamknij {
            get {
                return ResourceManager.GetString("Zamknij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamietaj mnie.
        /// </summary>
        public static string ZapamietajMnie {
            get {
                return ResourceManager.GetString("ZapamietajMnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string Zarejestruj {
            get {
                return ResourceManager.GetString("Zarejestruj", resourceCulture);
            }
        }
    }
}
